#ddev-generated
USER ${username}

RUN qemo-github-installer -u ajeetdsouza -r zoxide -U https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.8/zoxide-0.9.8-x86_64-unknown-linux-musl.tar.gz -b zoxide

USER root