#ddev-generated
USER ${username}

RUN qemo-github-installer -u jesseduffield -r lazygit -U https://github.com/jesseduffield/lazygit/releases/download/v0.53.0/lazygit_0.53.0_Linux_x86_64.tar.gz -b lazygit

USER root