# ddev-generated
USER ${username}

RUN qemo-github-installer -u sharkdp -r bat -U https://github.com/sharkdp/bat/releases/download/v0.25.0/bat-v0.25.0-x86_64-unknown-linux-gnu.tar.gz -b bat

USER root