#ddev-generated
RUN apt-get update -y && \
    apt-get install -y \
        libjemalloc2 \
        libncursesw5

USER ${username}

RUN qemo-github-installer -u aristocratos -r btop -U https://github.com/aristocratos/btop/releases/download/v1.4.4/btop-x86_64-linux-musl.tbz -b bin/btop

USER root