# ddev-generated
RUN apt-get update -y && \
    apt-get install -y \
        curl \
        nmap

USER ${username}

RUN qemo-github-installer -u bee-san -r RustScan -f "$(uname -m)-linux-rustscan.tar.gz.zip" -b rustscan

USER root