#ddev-generated
USER ${username}

RUN qemo-github-installer -u pemistahl -r grex -U https://github.com/pemistahl/grex/releases/download/v1.4.5/grex-v1.4.5-x86_64-unknown-linux-musl.tar.gz -b grex

USER root