# ddev-generated
USER ${username}

RUN qemo-github-installer -u Wilfred -r difftastic -U https://github.com/Wilfred/difftastic/releases/download/0.64.0/difft-x86_64-unknown-linux-gnu.tar.gz -b difft

USER root