#ddev-generated
USER ${username}

RUN qemo-github-installer -u denisidoro -r navi -U https://github.com/denisidoro/navi/releases/download/v2.24.0/navi-v2.24.0-x86_64-unknown-linux-musl.tar.gz -b navi

USER root